/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_treech_imagebeauty_NativeUtil */

#ifndef _Included_com_treech_imagebeauty_NativeUtil
#define _Included_com_treech_imagebeauty_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_treech_imagebeauty_NativeUtil
 * Method:    beauty
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_treech_imagebeauty_NativeUtil_beauty
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
